msg

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -126,8 +126,8 @@ jobs:
           name: Smoke Test
           command: |
             if [[ "$HTTPCODE" -ne 200 ]];then
-            echo "heroku app not responding, failing deploy"
-            exit 1
+            echo "heroku app not responding, failing deploy" \
+            exit 1 \
             HTTPCODE=`curl -s -o /dev/null -w "%{http_code}" https://$HEROKU_APP_NAME.herokuapp.com/`
             fi
 
